### PR TITLE
Add support for _metadata

### LINKED ISSUE #115: [JS] Missing support for _metadata
As the title implies, the js client is currently lacking support for the `_metadta` fields. 

I am working on a PR to resolve this, but I am currently not 100% sure about the structure of the _metadata field and couldn't find any resource on it. 
My working assumption is that _metadata only contains a `features` property that is structured like the `features` property of a thing. Is this correct or can there be additional fields inside the `_metadata` property of a thing?

I'd be great if someone could clarify that for me or point me to a complete description of the ditto schema if one exists!

### PR DESCRIPTION
**Pull request by vavido**
Adds a `_metadata` field to the thing model.

Closes #115

### CODE REVIEW

**Review by ffendt — COMMENTED** [review]
Hi @vavido,
thanks for your contribution! I think it'll be best to wait and review this PR after #116 is merged. Then we'll see only the changes regarding `Metadata` in here (but on first sight it looks quite promising 👍).

**Comment by vavido** [comment]
Hi @ffendt,
you are correct, as this PR also includes the changes from #116, it should be merged afterwards. 
I forgot to mention that in the PRs description, sorry

**Comment by ffendt** [comment]
Hi @vavido,

first of all thanks for working on this. I was finally able to have a second look at this and think there is still an open point here: Writing metadata for a Thing. 

In your implementation you're correctly deserializing the metadata when coming from Ditto. But just serializing the metadata and sending it to Ditto won't work for setting it. There's documentation on [setting metadata](https://www.eclipse.org/ditto/basic-metadata.html#setting-metadata) which describes that to set metadata, a special header containing a JSON array is used. I'm unsure if it would make sense creating the PUT representation of Metadata from the GET representation of it, as I don't know how we can e.g. analyze fast and easy where to set the special syntax `*/{key}`.

Btw: somehow still all changes from #116 are shown in the "Files changed" tab of the PR. Any idea on how to fix this?

**Comment by vavido** [comment]
Hi @ffendt,
currently we only have a need for reading metadata from ditto and are still not decided if we should implement this feature right now. 
Even if we do, we have more pressing issues in the next couple of weeks, so if you want to wait for the "other direction" to be implemented before merging this could take some time. 

My suggestion would be that we simply remove the serialization of the metadata, merge this PR and create a new Issue for the future to add support for metadata.
This way, the client at least offers read support for _metadata.

About the changes from #116: I'm not really sure, maybe there's a way to update the PR? I've almost exclusively worked with gitlab until now, sorry

**Comment by ffendt** [comment]
Hi @vavido,

your suggestion sounds reasonable to me. I'd be willing to merge this if you remove the serialization part.

**Comment by vavido** [comment]
I just removed the `_metadata` from the `toObject` method, I think this should be enough to avoid sending extraneous data to ditto.

**Comment by ffendt** [comment]
Hi @vavido,
thanks, that looks good now. Could you please resolve the conflicts with the master branch (field `definition` was added to `Thing`). I'd suggest moving `metadata` to the last position in the constructor as it is a new field (missed this before).

**Comment by vavido** [comment]
@ffendt Should finally be ready to merge now 😄

**Comment by ffendt** [comment]
Yep, thank you very much

**Review by ffendt — APPROVED** [review]

**Pull request merged**
