### PR TITLE
Remove the IIFE build from the API and DOM modules

### PR DESCRIPTION
**Pull request by ffendt**
Removes the IIFE build from API and DOM modules as ES6 modules can also be used in browsers instead.
Still TODO: find out how to bundle the API module into the DOM module, as the node-resolve plugin for rollup doesn't seem to do the job as expected.

### CODE REVIEW

**Comment by ffendt** [comment]
I just read a little about how bare imports (e.g. `import { HttpClientBuilder } from '@eclipse-ditto/ditto-javascript-client-api_1.0'`) can be used in browsers with ES6 modules and stumbled upon [import-maps](https://github.com/WICG/import-maps). This seems to be the perfect fit for the bundling problem mentioned above, but is not yet supported by browsers.
There are however some polyfills that already enable this functionality and I could actually get this running using [es-module-shims](https://github.com/guybedford/es-module-shims) against the local build of the client:

```
//...

<script defer src="https://unpkg.com/es-module-shims"></script>
<script type="importmap-shim">
{
  "imports": {
    "@eclipse-ditto/ditto-javascript-client-api_1.0": "./lib/api/dist/index.es.js"
  }
}
</script>
<script type="module-shim">
   import { DittoDomClient, DomHttpBasicAuth } from "./lib/dom/dist/index.js";

    const client =  DittoDomClient.newHttpClient()
        .withTls()
        .withDomain('https://ditto.eclipseprojects.io/')
        .withAuthProvider(DomHttpBasicAuth.newInstance("username", 'password'))
        .apiVersion2()
        .build();
    client.getThingsHandle().getThing("foo:bar");
</script>
//...
```

I think we'll need to wait for some more committers to come back from holidays and share their opinion if that's enough browser support.

**Comment by ffendt** [comment]
@vavido: What would you think if we would also bundle the API directly into the dom and node implementation. There would be no need for users to have a separate dependency on the api module. Also, there would be no need for import-maps when using it directly in a browser.

**Comment by vavido** [comment]
@ffendt That's a very good idea, I don't think there is a reason anyway why one would want to use the DOM/Node implementation without the base API.

**Comment by ffendt** [comment]
Then I think that will be the way we go. I'm unsure when we'll be able to do this, so it might some time though.

**Review by jokraehe — APPROVED** [review]
LGTM

**Pull request merged**
