### PR TITLE
fix PUT request for existing thing

### LINKED ISSUE #61: [JS] putThing throws error when updating an existing Thing
According to the docs, a `PUT` request for an existing `Thing` will have ditto respond with status 204 and an empty body.
The JS client SDK, however, always expects body: https://github.com/eclipse/ditto-clients/blob/master/javascript/lib/api/src/client/request-factory/request-sender.ts#L48

### PR DESCRIPTION
**Pull request by vhdirk**
Fixes #61

### CODE REVIEW

**Comment by ffendt** [comment]
Hi there,

thanks for the PR and sorry for letting you wait. Wouldn't it be easier to not parse the response at all in case of a 204 (probably in the line you mentioned in #61: https://github.com/eclipse/ditto-clients/blob/master/javascript/lib/api/src/client/request-factory/request-sender.ts#L48)?
Afaik, Ditto will never return a body on 204 responses (which is also what the 204 is meant for). Actually, i guess it would be faulty to parse the body of a 204 at all.

**Comment by vhdirk** [comment]
TBH, I had these commits in a stash somewhere, I and was convinced I solved it like you explain. Turns out I didn't :)
I'll refactor this when I have more time.

**Comment by ffendt** [comment]
Is there a reason you are changing the return types instead of just writing `return new PutResponse(null, response.status, response.headers)`?

**Comment by thjaeckle** [comment]
@vhdirk did you have a look at @ffendt's comment?
We would like to get this merged :)

**Comment by thjaeckle** [comment]
Please also add your company to the copyright holders in https://github.com/eclipse/ditto-clients/blob/master/legal/NOTICE.md

**Comment by vhdirk** [comment]
Sorry for the delay. I finally got round to fixing this.

**Comment by ffendt** [comment]
Hi @vhdirk,

no problem, thanks for going at it again. I had a look and the implementation seems fine.

I think it makes sense to verify the new behavior in tests, so it isn't broke by accident later. The tests should be adjusted so for every `PUT` test with "created"-outcome (201) there is also a second test with the "modified"-outcome (204).

E.g. 
```
// current test
it('puts a Thing which is created', () => {
    return H.test({
      toTest: () => handleV2.putThing(H.thing),
      testBody: H.thing.toObject(),
      expected: new PutResponse(H.thing, 201, undefined),
      request: `${baseRequest}`,
      method: 'put',
      status: 201,
      payload: H.thing.toJson()
    });
  });
// additional test
  it('puts a Thing which is modified', () => {
    return H.test({
      toTest: () => handleV2.putThing(H.thing),
      testBody: H.thing.toObject(),
      expected: new PutResponse(null, 204, undefined),
      request: `${baseRequest}`,
      method: 'put',
      status: 204,
      payload: H.thing.toJson()
    });
  });
```
For those tests to work there's also a small bugfix needed in `tests/client/http/http-requester.mock.ts#doRequest`:
```
public doRequest(method: string, url: string, header: Map<string, string>, body: string): Promise<GenericResponse> {
    // ...
        if (this.matches(method, url, header, body, request)) {
          // remove entry for this request
          this.requests.delete(request);
          resolve(response);
    // ...
```
Can you spare some more time to implement these tests?

**Review by ffendt — APPROVED** [review]
Just added the remaining tests for the other PUT resources. LGTM now, tanks a lot 👍 . This will probably end up in the upcoming 3.0.0 (#121).

**Comment by vhdirk** [comment]
Ok, cool! Thanks!

**Pull request merged**
