### PR TITLE
Fix http connection

### PR DESCRIPTION
**Pull request by IrishWhiskey**
Fix the rest implementation bug discussed in #155

### CODE REVIEW

**Comment by ffendt** [comment]
Hi @IrishWhiskey,

thank you very much for your PR. I'll have a look at it and get back to you (sorry for taking so long).

**Comment by ffendt** [comment]
Hi @IrishWhiskey,

your changes look very good. I'm just additionally adapting the `ProxyAgent` to also work without tls, then this is ready to merge. Good job, thank you 👍

**Comment by ffendt** [comment]
@IrishWhiskey, can you verify if the rest implementation still works on your side?

**Comment by IrishWhiskey** [comment]
Hi @ffendt. It works for me. Thanks for helping me :)

**Pull request merged**
